### ISSUE TITLE
Search results are ranked in no apparent useful order to the customer

### ISSUE THREAD

**Issue by joshua-bouv** [everyday-as/pivity-issues#1096]
### The feature: 

Making it so that results from a search for an addon are ranked from likely to be of high quality to of lower quality, whether that be based on its reviews, sales, popularity, freshness etc. 

### The reasoning: 

This would be both beneficial to the customer as they can see the best addons first **and** to new & (active) old content creators as addons that are popular (short & long term) and supported would be prioritised. 

### Things that might be important are:

- Is the addon marked as supported?
- Does the script have media and a description?
- Is the addon popular (taking into account both sales and how recently it was added to the market)?
- Has the addon received an update recently?
- Does it have more than X amount of reviews (to prevent 1 five star review being better than 20 five star reviews and 1 four star review)?
- If so what is the review rating?

### Additional Information

Currently it looks like the following;

---------------------------------------------------------

When comparing public statistics from the top 2 results after searching "event":

![image](https://user-images.githubusercontent.com/17968553/129500161-bfb7732b-0072-449c-9d49-2b64ddb8a9df.png)

In this case, the 2nd result performs better on every public statistic compared to the 1st result, meaning the results should probably be flipped.

---------------------------------------------------------

Looking at another more detailed example is for searching "report":

![image](https://user-images.githubusercontent.com/17968553/129500225-55695684-7dcc-4fa1-825d-3b3385564171.png)

As you can see the top 3 results are all unsupported, 2 of them not receiving an update for over 3 years. Whilst this doesn't necessarily mean they are bad, looking at other statistics in comparison like the low amount of reviews, review ratings and sales* (to indicate its popularity) makes them weaker options when compared to results 4 and 5.

*Sales should probably take into account how long the addon has been on sale for it to be useful metric

**Comment by TheodoorP** [comment]
We've redone the way search is done and it should now give better results :)
