### ISSUE TITLE
Always sort content creators first in search users list

### ISSUE THREAD

**Issue by WilliamVenner** [everyday-as/pivity-issues#1098]
### Feature

Most customers will be using the search feature to look for content creators(+), it makes the most sense to sort them first.

At the very least, a sort by reputation feature would be very useful for finding people with short usernames.

**Comment by LucaTanks** [comment]
I partly agree here, as when I search Billy you come up 10th. I think it would be better to sort primarily by rep than rank

**Comment by TheodoorP** [comment]
Searching users is now partially sorted by rep.
