### ISSUE TITLE
Notify users when wishlist addon goes on sale

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/pivity-issues#1120]
### Feature

Send a notification to users when an addon from their wishlist is added to a sale.

Example: An addon on your wishlist is on sale! <addon name> is currently x% off!

Clicking on the notification brings the user directly to the addon page.

### Additional Information

This feature adds incentive for customers to buy addons on their wishlist.

**Comment by TheodoorP** [comment]
Added in the latest version 🚀
