### ISSUE TITLE
Incorrect sort order when searching in tickets

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/pivity-issues#1196]
### Expected Behavior

That it sorts by "last activity" like usual

### Actual Behavior

It does not sort by "last activity" when you type something in the search bar for tickets.
Example: https://www.gmodstore.com/dashboard/tickets?addon=all&label=all&status=all&state=all&search=notification

https://i.imgur.com/JnOP2gr.png

### Reproduction Steps

```markdown
1. Go to your dashboard tickets
2. Type something in the search field
3. Select "all tickets"
```

**Comment by TheodoorP** [comment]
Can you still replicate this issue?

**Comment by Crap-Head** [comment]
> Can you still replicate this issue?

No, it now sorts by "last activity" when searching in tickets.
Thanks!
