### ISSUE TITLE
Sales end date max is incorrectly calculated

### ISSUE THREAD

**Issue by LivacoNew** [everyday-as/pivity-issues#1221]
### Expected Behavior

The max end date from sale is 2 weeks from the starting date from sale. Makes sense.

### Actual Behavior

The max end date from a sale is 2 weeks... from the current time. It doesn't care about the starting date of the sale, meaning I can't make my haloween sales, meaning I'm not happy :(
Confirmed this to not just be me, seems to be a global site issue.

![](https://upload.livaco.dev/u/dFGWpnlx0f.png)

### Reproduction Steps

```markdown
1. Make addon
2. Make sale that ends in > 2 weeks from your current time
3. Loss.
```

### Browsers

Firefox 105.0.3 (64-bit)

### Example URL

https://www.gmodstore.com/dashboard/teams/GBcrSGwgQLe5fImt2FscuA/sales/manage

### GmodStore Version

v11.6.1

**Comment by TheodoorP** [comment]
I can no longer replicate this issue, if it still occurs feel free to reopen this issue 😄

**Comment by LivacoNew** [comment]
This is still happening on my end, only letting me have 7 days after the sale start.

![image](https://github.com/user-attachments/assets/edf0cb52-b465-4c6c-8292-57536cf7d783)
![image](https://github.com/user-attachments/assets/d683f953-ad98-4482-add9-447a679da48f)

**Comment by TheodoorP** [comment]
Hmmm strange, I'll retest this tonight.

**Comment by TheodoorP** [comment]
I'm still unable to replicate this locally, laravel js validation must be misbehaving on my end. 

I've applied a fix which should fix your validation problem (version 18.4.2), could you confirm that the issue is gone? 😄

**Comment by LivacoNew** [comment]
Still there
![image](https://github.com/user-attachments/assets/73eadd1d-005e-4c14-9ce8-3d4a303eb50b)

I've noticed that this is only when it's doing the "realtime" clientside validation. Sometimes that validation breaks and doesn't say anything, allowing me to submit the form and your serverside validation gets it right allowing me to make a sale correctly.

![image](https://github.com/user-attachments/assets/a5e364f0-3506-41d4-b2b6-0d9cd202ee41)

 When that wrong clientside validation gets in the way though your not allowed to submit the form at all.

**Comment by TheodoorP** [comment]
Your observation is correct, it is indeed the clientside validation that is making the submission fail. I should've disabled the clientside validation on that field, did you verify the version I mentioned was already live by the time you tested?

**Comment by LivacoNew** [comment]
Seems to be now ye, sorry forgot to CTRL + F5

**Comment by TheodoorP** [comment]
Great, glad to hear 😀
