### ISSUE TITLE
Can't get slug property

### ISSUE THREAD

**Issue by hugoheml** [everyday-as/pivity-issues#1238]
### Expected Behavior

The slug property must be added on all endpoints where we can see product data

### Actual Behavior

I can't get the slug property:
![image](https://user-images.githubusercontent.com/51268820/215276419-cdeb4559-08b6-4881-905f-9c0b6b4ca093.png)

### Reproduction Steps

```markdown
1. Call an API endpoint which returns an product data
```

### Example URL

https://www.gmodstore.com/api/v3/products/0bfa7c6e-0f6c-4756-928b-083281ad04b3

### GmodStore Version

v12.5.14

**Comment by TheodoorP** [comment]
Fixed in the next release.
