### ISSUE TITLE
OpenAPI does not map product description.

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/pivity-issues#1247]
### Expected Behavior

OpenAPI schema should map the product "description" and "shortDescription" fields, as returned by the API.

### Actual Behavior

Currently, it only maps the "shortDescription" field.

### Reproduction Steps

```markdown
1. Generate an OpenAPI SDK.
2. Fetch a product.
```

### Browsers

OpenAPI Generator CLI 6.2.1, OpenAPI Schema Version 3.0.0

### Example URL

https://gmodstore.com/api/v3/products/9cfd2f92-59be-44b7-a7e0-565ca829ae73

### GmodStore Version

v13.1.5

**Comment by TheodoorP** [comment]
Fixed in the next release.
