### ISSUE TITLE
Addon Media Previews are Broken

### ISSUE THREAD

**Issue by LivacoNew** [everyday-as/pivity-issues#1249]
### Expected Behavior

The addon media previews all work

### Actual Behavior

Everything aside from Listing Image is empty
![](https://upload.livaco.dev/u/I6ot4ErLAF.png)

### Reproduction Steps

```markdown
1. Make an addon
2. Look at the media page
```

### Browsers

Firefox 110.0.1 (64-bit)

### Example URL

https://www.gmodstore.com/dashboard/addons/better-banking/media

### GmodStore Version

v13.1.6

**Comment by TheodoorP** [comment]
The previews seem to be working appropriately again. If this is still happening to you feel free to reopen this issue.
