### ISSUE TITLE
addon rating score gets rounded down in star representation

### ISSUE THREAD

**Issue by timmybo5** [everyday-as/pivity-issues#1255]
### Expected Behavior

How it works right now is that only a perfect 5 score shows 5 stars, it's the first thing a potential customers looks at. 
It would be more fair to round up/down to the nearest, e.g 4.8 -> 5 stars, 4.6 -> 4.5 stars

![image](https://user-images.githubusercontent.com/4988198/232024630-bdacad60-05a9-4ccc-a705-f4ba1a307f25.png)
![image](https://user-images.githubusercontent.com/4988198/232024644-8712876e-8cff-49f3-a66a-548d9be8c5f3.png)

**Comment by MenschlichTv** [comment]
Agreed, similar on one of my addons as well 
![image](https://user-images.githubusercontent.com/34013112/232035662-bee8c5e9-bb6c-449c-8dc0-010589a4018b.png)
![image](https://user-images.githubusercontent.com/34013112/232035684-19494475-84aa-443a-9742-dde4eb3098ee.png)

**Comment by TheodoorP** [comment]
This has been fixed in a previous release.
