### ISSUE TITLE
User bound to coupons not showing

### ISSUE THREAD

**Issue by Lythium4848** [everyday-as/pivity-issues#1266]
### Expected Behavior

The bound user to show where the bound users search box is

### Actual Behavior

Nothing gets shown

### Reproduction Steps

```markdown
1. Create a coupon that is bound to a user
```

### Example URL

https://www.gmodstore.com/dashboard/addons/{{addon-name}}/coupons/{{coupon}}/create

### GmodStore Version

v14.9.1

**Comment by Marcuzz** [comment]
Fixed in the next version.
