### ISSUE TITLE
Various UI problems

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/pivity-issues#1284]
### Expected Behavior

This happened after the navbar changes afaik

### Actual Behavior

https://www.gmodstore.com/dashboard/teams/excNlEGGSGGuYmrAvqw1BQ/users
![image](https://github.com/everyday-as/gmodstore-issues/assets/4314483/e31629a7-5494-4d61-ad99-9e793c388343)

https://www.gmodstore.com/dashboard/addons/npc-shops-in-game-setup-unlimited-shops-job-restrictions-all-gamemodes/requirements
![image](https://github.com/everyday-as/gmodstore-issues/assets/4314483/6e38bb48-3054-4e89-b14f-33913de8afba)

https://www.gmodstore.com/dashboard/addons/npc-shops-in-game-setup-unlimited-shops-job-restrictions-all-gamemodes/versions/create
![image](https://github.com/everyday-as/gmodstore-issues/assets/4314483/aa1adfdd-2a5d-4526-b2ed-873d535a5dec)

![image](https://github.com/everyday-as/gmodstore-issues/assets/4314483/6673d3e6-001b-4c43-a8c6-7f6f4a7aa8e3)

Just a bunch of misalignment and missing spaces after that update I've noticed around the site and thought I would compile a quick list of the obvious ones. There's more if you look closer.

### Reproduction Steps

```markdown
1. Browse
2. The
3. Site
```

**Comment by Marcuzz** [comment]
Thanks.

We're working on getting rid of bootstrap, and adding Tailwind. Adding Tailwind's normalization resets caused a bunch of these kinds of issues - we'll get around to fixing them :D

**Comment by Crap-Head** [comment]
![image](https://github.com/everyday-as/gmodstore-issues/assets/4314483/b2899737-ac01-4d58-b3c9-5726c3afca87)
Also this

**Comment by Crap-Head** [comment]
A lot here
![image](https://github.com/everyday-as/gmodstore-issues/assets/4314483/8eb7d2ce-35ba-4e56-9ce8-20e9d7fe0ae7)

**Comment by Marcuzz** [comment]
All of the visual issues in this issue so far are now fixed in the next release.

**Comment by Crap-Head** [comment]
All the above has silently been fixed.

You can close this issue
