### ISSUE TITLE
Incorrect link on create new job page.

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/pivity-issues#1295]
### Expected Behavior

https://www.gmodstore.com/help/getting-started/topics/job-guidelines-tips-submissions-and-applications linked for guidelines first.
https://www.gmodstore.com/help/getting-started/topics/job-practices-avoiding-scammers linked for practices after.

### Actual Behavior

https://www.gmodstore.com/community/threads/nBK106AXT56EHeSOfCFMGg and
https://www.gmodstore.com/help/getting-started/topics/qb15GqfUTrW0KD_ap0Qmcw linked.

### Reproduction Steps

```markdown
Open job page
```

### Example URL

https://www.gmodstore.com/jobmarket/jobs/create

### GmodStore Version

v17.1.2

**Comment by TheodoorP** [comment]
Fixed in a previous release.
