### ISSUE TITLE
Customer message when opening ticket is broken

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/pivity-issues#1298]
### Expected Behavior

That it doesn't show the empty box and shows a message to customers

### Actual Behavior

Is that empty box supposed to show the message for customers if not empty?

![image](https://github.com/everyday-as/gmodstore-issues/assets/4314483/98335b21-6174-48e3-bb85-8c08ae6e8608)
![image](https://github.com/everyday-as/gmodstore-issues/assets/4314483/5fe41442-022d-4746-8f21-b57b642b4243)
![image](https://github.com/everyday-as/gmodstore-issues/assets/4314483/3cab2473-dac1-4311-b458-4008558296ed)

### Reproduction Steps

```markdown
1. Try to submit a ticket to different addons to see different behavior
```

### GmodStore Version

v17.1.3

**Comment by TheodoorP** [comment]
Fixed in next release.
