### ISSUE TITLE
Dahsboard always shows numbers as negative (red)

### ISSUE THREAD

**Issue by MenschlichTv** [everyday-as/pivity-issues#1299]
### Expected Behavior

Depending if your last month was better or worse, it should be displayed green (+ icon) or red (- icon)

### Actual Behavior

Even if the last month has better numbers, it will be displayed red with a minus icon.

### Reproduction Steps

```markdown
1. Go to https://www.gmodstore.com/dashboard
2. Everything is red no matter the numbers
```

**Comment by TheodoorP** [comment]
A better month should result in a better dashboard after the next release😄
