### ISSUE TITLE
Reskin - Logo missing on firefox

### ISSUE THREAD

**Issue by 0wain** [everyday-as/pivity-issues#1303]
### Expected Behavior

The logo to show

### Actual Behavior

The logo doesn't show on firefox.

![Screenshot_2024-08-08_at_22 40 43](https://github.com/user-attachments/assets/686057fd-f5e2-4d35-a3ad-b546bef5c658)
![Screenshot_2024-08-08_at_22 42 53](https://github.com/user-attachments/assets/ed43f256-8e56-4ab1-b854-c52fee4986a8)

### Reproduction Steps

```markdown
1. Use firefox.
2. Go to any of the rebranded pages.
```

### Browsers

Firefox 129 - 64 Bit

### Example URL

https://www.gmodstore.com/community

### GmodStore Version

v18.0.8 

### Additional Information

The dark mode on the rebrand needs some serious love. It's disorienting and there's no content priority on a lot of pages. Things just blend together. The `/community` page is a good example, everthing has the same color depth so it's headache enducing to read. Needs some quality control.

**Comment by Marcuzz** [comment]
Hi,

Thank you for the feedback!

The logo is on it's way back on Firefox, and we've made some tweaks to the colours for the Pivity dark theme.

There will be more adjustments to the Pivity theme as we move forward, you are right that it is missing key design features in the dark theme. We haven't quite landed out how this branding should look on a dark theme yet.

**Comment by TheodoorP** [comment]
Logo is back on firefox :)
