### ISSUE TITLE
Product multitenancy

### ISSUE THREAD

**Issue by kekalainen** [everyday-as/pivity-issues#1306]
### Feature

Products should be many-to-many mappable to multiple tenants (rather than being confined to a single store).

![dashboard mockup](https://github.com/user-attachments/assets/5ba49233-fb27-4ed0-b6e3-ef876e3a69b0)

### Additional Information

This is primarily useful for web products which integrate with multiple games.

Creating a duplicate product for each store is not a feasible workaround due to e.g. reviews, comments, knowledge bases, purchases and ticket quick replies being scoped to each instance separately.

**Comment by TheodoorP** [comment]
We're working on adding support for multi-tenant products. More information will follow soon 😊

**Comment by TheodoorP** [comment]
We have implemented a way to have your product be displayed on multiple marketplaces. 

Please contact us through a site ticket and link your products, we'll make them available on the Rust store 😄
