### ISSUE TITLE
Posting 2 or more replies after each other glitches the text box

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/pivity-issues#1314]
### Expected Behavior

Posting 2 or more replies after each other glitches the text box as shown in the attached video.

There also seem to be more issues with editing replies if you don't refresh the page as shown in the video.

https://youtu.be/NDYE0w5WpiI

### Actual Behavior

It should behave properly.

### Reproduction Steps

```markdown
1. Open a ticket
2. Try to make a few replies after each other and press ENTER to make a new line
```

### Browsers

Chrome

### Example URL

https://www.gmodstore.com/help/tickets/view/iFpElMTKSZaeIlhOlBgE5Q

### Pivity Marketplace Version

v18.12.11

**Comment by Marcuzz** [comment]
This should be fixed in the next release (deploying now).
