### ISSUE TITLE
Incorrect comment deletion logs.

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/pivity-issues#1317]
### Expected Behavior

When deleting a user's comment as a moderator, the event log is registered as "Commenter deleted a comment on Product", instead of "Moderator deleted Commenter's comment on Product"

### Actual Behavior

-

### Reproduction Steps

```markdown
Delete comment as a moderator.
```

### Browsers

Chrome Mainline

### Example URL

See Internal

### Pivity Marketplace Version

18.14.12

**Comment by Marcuzz** [comment]
Fixed in the next release, however, old events are not fixable 😢
