### ISSUE TITLE
Forum Reactions Don't Load

### ISSUE THREAD

**Issue by LivacoNew** [everyday-as/pivity-issues#1318]
### Expected Behavior

The icons to react to a forum post load

### Actual Behavior

![image](https://github.com/user-attachments/assets/0f87ac9a-8822-412e-a6ba-2df94c79d4f8)

Going to the [raw url](https://media.gmodstore.com//assets/img/forum/ratings/confused.svg) of one of them, it's access denied
![image](https://github.com/user-attachments/assets/392a73b4-ac0d-4a51-a958-b3f16adb7030)

This just looks like it's going to the wrong directory as already-applied reactions work fine, e.g;
- https://media.gmodstore.com/_/build/img/forum/ratings/wastebin.svg < works, from a reaction already applied by someone else
- https://media.gmodstore.com//assets/img/forum/ratings/confused.svg < doesn't work, from the selection to add one yourself

### Reproduction Steps

```markdown
1. Go to a forum post
```

### Browsers

Both Firefox 131.0.2 (64-bit) & Chromium 129.0.6668.100

### Example URL

https://www.gmodstore.com/community/threads/d5OXzuRySpiSAqaj_YLf8Q/page/1#post-c08249f1-0903-4432-84da-2d531d00b2dc

### Pivity Marketplace Version

v18.17.3

**Comment by Marcuzz** [comment]
Thanks for reporting this issue. A fix is rolling out :)
